export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_FAILURE = 'FETCH_QUIZES_FAILURE';

export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'FETCH_QUIZ_FAILURE';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const RETRY_QUIZ = 'RETRY_QUIZ';

export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const FINISH_CREATE_QUIZ = 'FINISH_CREATE_QUIZ';
export const FINISH_CREATE_QUIZ_SUCCESS = 'FINISH_CREATE_QUIZ_SUCCESS';
export const FINISH_CREATE_QUIZ_FAILURE = 'FINISH_CREATE_QUIZ_FAILURE';
